# Generated by Django 3.0.7 on 2020-07-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], max_length=7),
        ),
    ]
